[package]
name = "rust_book_ch15_01_smart_pointers_deref"
version = "0.1.0"
authors = ["Tony McNeil <mcneil.tony@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
