[package]
name = "rust_book_ch09_01_errors_painc"
version = "0.1.0"
authors = ["Tony McNeil <mcneil.tony@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
